[package]
name = "mate-conjecture"
version = "0.1.0"
edition = "2024"

[dependencies]
binary-search = "0.1.3"
rayon = "1.11.0"
rug = "1.28.0"

[profile.release]
lto = true
# panic = "abort"
codegen-units = 1
strip = true
opt-level = 3
